set(_CATKIN_CURRENT_PACKAGE "tomato_seg")
set(tomato_seg_VERSION "0.0.0")
set(tomato_seg_MAINTAINER "chen <chen@todo.todo>")
set(tomato_seg_PACKAGE_FORMAT "1")
set(tomato_seg_BUILD_DEPENDS "visualization_msgs")
set(tomato_seg_BUILD_EXPORT_DEPENDS "visualization_msgs")
set(tomato_seg_BUILDTOOL_DEPENDS "catkin")
set(tomato_seg_BUILDTOOL_EXPORT_DEPENDS )
set(tomato_seg_EXEC_DEPENDS "visualization_msgs")
set(tomato_seg_RUN_DEPENDS "visualization_msgs")
set(tomato_seg_TEST_DEPENDS )
set(tomato_seg_DOC_DEPENDS )
set(tomato_seg_DEPRECATED "")