set(_CATKIN_CURRENT_PACKAGE "rgbtocloud")
set(rgbtocloud_VERSION "0.0.0")
set(rgbtocloud_MAINTAINER "chen <chen@todo.todo>")
set(rgbtocloud_PACKAGE_FORMAT "1")
set(rgbtocloud_BUILD_DEPENDS "jsk_recognition_msgs" "geometry_msgs")
set(rgbtocloud_BUILD_EXPORT_DEPENDS "jsk_recognition_msgs" "geometry_msgs")
set(rgbtocloud_BUILDTOOL_DEPENDS "catkin")
set(rgbtocloud_BUILDTOOL_EXPORT_DEPENDS )
set(rgbtocloud_EXEC_DEPENDS "jsk_recognition_msgs" "geometry_msgs")
set(rgbtocloud_RUN_DEPENDS "jsk_recognition_msgs" "geometry_msgs")
set(rgbtocloud_TEST_DEPENDS )
set(rgbtocloud_DOC_DEPENDS )
set(rgbtocloud_DEPRECATED "")