set(_CATKIN_CURRENT_PACKAGE "tomato_detect")
set(tomato_detect_VERSION "0.0.0")
set(tomato_detect_MAINTAINER "chen <chen@todo.todo>")
set(tomato_detect_PACKAGE_FORMAT "1")
set(tomato_detect_BUILD_DEPENDS "rgbtocloud" "tomato_seg" "pose_reasoning")
set(tomato_detect_BUILD_EXPORT_DEPENDS "rgbtocloud" "tomato_seg" "pose_reasoning")
set(tomato_detect_BUILDTOOL_DEPENDS "catkin")
set(tomato_detect_BUILDTOOL_EXPORT_DEPENDS )
set(tomato_detect_EXEC_DEPENDS "rgbtocloud" "tomato_seg" "pose_reasoning")
set(tomato_detect_RUN_DEPENDS "rgbtocloud" "tomato_seg" "pose_reasoning")
set(tomato_detect_TEST_DEPENDS )
set(tomato_detect_DOC_DEPENDS )
set(tomato_detect_DEPRECATED "")